language: node_js
sudo: require
services:
  - docker
node_js:
  - "6"
before_install:
  - docker build -t actano/nextbot .
script:
  - docker run actano/nextbot npm run lint
  - docker run actano/nextbot npm test